version: "3.4"
name: rbmdkrfinalapp
services:
  postgres:
    image: postgres:9.6.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./results/telemetry_postgresql.sql:/docker-entrypoint-initdb.d/telemetry_postgresql.sql
    environment:
      POSTGRES_PASSWORD: "speedtest"
      POSTGRES_USER: "speedtest"
      POSTGRES_DB: "speedtest"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U speedtest -d speedtest" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - traefik-public
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: db
  librespeed:
    build: .
    depends_on:
      - postgres
    env_file:
      - speed.env
    networks:
      - traefik-public
    ports:
      - 8000:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app
    volumes:
      - $PWD/docker/servers.json:/servers.json
    labels:
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.http.routers.web.rule=Host(`librespeed.159.253.18.53.nip.io`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.services.web.loadbalancer.server.scheme=http"
      - "traefik.http.middlewares.web.headers.customrequestheaders.X-Real-IP=$remote_addr"
  traefik:
    image: traefik:v2.10
    ports:
      - 8080:8080
      - 80:80
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.http.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: traefik
networks:
  traefik-public:
    name: traefik-public
    external: true
volumes:
  pgdata:

