version: "3.4"
name: rbmdkrfinalapp
services:
  postgres:
    image: postgres:9.6.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./results/telemetry_postgresql.sql:/docker-entrypoint-initdb.d/telemetry_postgresql.sql
    environment:
      POSTGRES_PASSWORD: speedtest
      POSTGRES_USER: speedtest
      POSTGRES_DB: speedtest
    networks:
      - traefik-public
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: db
  librespeed:
    build: .
    depends_on:
      - postgres
    env_file:
      - speed.env
    networks:
      - traefik-public
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app
    volumes:
      - $PWD/docker/servers.json:/servers.json
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.librespeed.rule=Host(`librespeed.159.253.18.53.nip.io`)"
        - "traefik.http.routers.librespeed.entrypoints=web"
        - "traefik.http.services.librespeed.loadbalancer.server.port=80"
        - "traefik.http.services.librespeed.loadbalancer.server.scheme=http"
  traefik:
    image: traefik:v2.0
    ports:
      - 80:80
      - 8080:8080
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: traefik
networks:
  traefik-public:
    name: traefik-public
    external: true
volumes:
  pgdata:

