#file: noinspection ComposeUnknownKeys
version: '3.4'
name: rbmdkrfinalefk
services:
  fluentd:
    build: ./fluentd
    hostname: fluentd
    environment:
      - ESHOST=elasticsearch
      - ESPORT=9200
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      traefik-public:
  elasticsearch:
    image: elasticsearch:8.8.0
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "discovery.seed_hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "network.host=0.0.0.0"
      - "ELASTIC_PASSWORD=test"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.collection.enabled=true"
      - "xpack.security.audit.enabled=false"
      - "xpack.license.self_generated.type=trial"
    ports:
      - "9200:9200"
    networks:
      traefik-public:
  kibana:
    image: kibana:8.8.0
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=elastic/kibana"
      - "ELASTICSEARCH_PASSWORD=test"
      - "SERVER_NAME=kibana"
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      traefik-public:

networks:
  traefik-public:
    name: traefik-publik
