version: '3.4'
name: efk
services:
  fluentd:
    build: ./fluentd
    depends_on:
      - elasticsearch
    environment:
      - ESHOST=elasticsearch
      - ESPORT=9200
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - traefik-public
  elasticsearch:
    image: elasticsearch:8.8.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=test
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=false
      - xpack.license.self_generated.type=trial
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - traefik-public
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
  kibana:
    image: kibana:8.8.0
    depends_on:
      - fluentd
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic/kibana
      - ELASTICSEARCH_PASSWORD=test
      - SERVER_NAME=kibana
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: kibana
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
    ports:
      - "5601:5601"
    networks:
      - traefik-public
volumes:
  esdata:
    name: esdata
networks:
  traefik-public:
    name: traefik-public