#file: noinspection ComposeUnknownKeys
version: '3.4'
name: rbmdkrfinalefk
services:
  fluentd:
    build: ./fluentd
    environment:
      - ESHOST=elasticsearch
      - ESPORT=9200
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      traefik-public:
  elasticsearch:
    image: elasticsearch:8.8.0
    hostname: elasticsearch
    environment:
      - node.name={{.Node.Hostname}}
      - discovery.seed_hosts=elasticsearch
      - ELASTIC_PASSWORD=test
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=false
      - xpack.license.self_generated.type=trial
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"
    networks:
      traefik-public:
  kibana:
    image: kibana:8.8.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic/kibana
      - ELASTICSEARCH_PASSWORD=test
      - SERVER_NAME=kibana
      - "NODE_OPTIONS=--max-old-space-size=512"
    ports:
      - "5601:5601"
    networks:
      traefik-public:

networks:
  traefik-public:
    name: traefik-publik