#file: noinspection ComposeUnknownKeys
version: '3.4'
name: rbmdkrfinalefk
services:
  fluentd:
    build: ./fluentd
    environment:
      - ESHOST=elasticsearch
      - ESPORT=9200
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      traefik-public:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    hostname: elasticsearch
    environment:
      - "network.host=0.0.0.0"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"
    networks:
      traefik-public:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    environment:
      - NODE_OPTIONS="--max-old-space-size=512"
    ports:
      - "5601:5601"
    networks:
      traefik-public:

networks:
  traefik-public:
    name: traefik-publik
